# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y nodejs
    finally:
      - echo This always runs even if the update or install command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm ci
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      -

artifacts:
  files:
    - '**/*'

